name: Feature Request
description: Don't ask for stupid shit/shit I'll already do
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added to the mod?
    validations:
      required: true
